# Основы линейной алгебры
## Работа с векторами

In [58]:
import numpy as np
import random as round
import scipy.linalg as lp

In [59]:
base_list1 = [1,2,3,4,5]
base_list2 = [[1,2,3],[4,5,6],[7,8,9]]
base_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [60]:
def f1(x):
    return x *x
projection = list (map (f1, base_list1))
projection1 = list (map(lambda x: x*2, base_list1))
projection
projection1

[2, 4, 6, 8, 10]

In [61]:
base_list3 = [43] * 5
base_list4 = [{1,2,3}] * 3
base_list4


[{1, 2, 3}, {1, 2, 3}, {1, 2, 3}]

In [62]:
XX = np.array([1,2,3])
YY = np.array(base_list2)
aa = np.arange(1, 10, 2)
bb = np.linspace(1, 10, 8)
bb

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

# Алгебра матриц

### Умножение матрицы на вектор

In [63]:
def Matrix2Vector(A, a):
    n, m = np.shape(A)

    b = [0] * n
    for i in range(0, n): #Для всех строк матрицы рассчитываем ячейки вектора результата
        s = 0
        for j in range(0, m): # номер элемента в строке
            s += A[i,j] * a[j]
        b[i] = s
    return b
A = np.array(base_list2)
b1 = Matrix2Vector(A,[1,2,3])
b1

[14, 32, 50]

## Транспонирование матрицы

In [64]:
def Transpose(A):
    n, m = np.shape(A)
    B = []
    for j in range (0, m): # перебираем номера столбцов матрицы А
         b = []
         for i in range(0, n):
              b.append(A[i,j])
         B.append(b)
    return np.array(B)

B = Transpose(A)
B


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

##  Простейшие операции

In [65]:
C = A * B
D = A
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Умножение матрицы на матрицу

In [75]:
def Matrix2Matrix(A,B):
    la = np.shape(A)
    lb = np.shape(B)

    C = []
    for i in range(0, lb[1]):
        C.append([0] * la[0])

    for i in range(0, la[0]):
        for j in range(0,lb[1]):
            s = 0
            for k in range(0, la[1]): # к - номер ячейки строки А и номер ячейки столбца Б
                s += A[i,k] * B[k,j]
            C[i][j] = s
        
    return np.array(C)

C = Matrix2Matrix(A, A.T)
print(B), print(A), C

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


(None,
 None,
 array([[ 14,  32,  50],
        [ 32,  77, 122],
        [ 50, 122, 194]]))

In [76]:
def Triangle(A):
    M = np.array(A)
    n, m = np.shape(M)

    d = 1
    rank = min (n,m)